spring:
  application:
    name: pulsescope-backend
  profiles:
    default: dev
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/pulsescope}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    show-sql: true

server:
  error:
    include-message: always

management:
  endpoints:
    web:
      exposure:
        include: health,info

springdoc:
  swagger-ui:
    path: /swagger-ui.html

integration:
  external-api:
    base-url: ${EXTERNAL_API_BASE_URL:https://gnews.io/api/v4}
    api-key: ${GNEWS_API_KEY:4d50cd51a7aa788a522b985077f62d70}
    language: ${GNEWS_LANGUAGE:en}
    country: ${GNEWS_COUNTRY:us}
    max-results: ${GNEWS_MAX_RESULTS:10}
  analysis-api:
    base-url: ${ANALYSIS_API_BASE_URL:http://localhost:8082}
  alpha-vantage:
    base-url: ${ALPHA_VANTAGE_BASE_URL:https://www.alphavantage.co/query}
    api-key: ${ALPHA_VANTAGE_API_KEY:FJDYXVSV53ZGQJ8K}
